restaurant/Controllers/PayController.cs
using Models.DAO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using Models.EF;
using PagedList;
using System.IO;

namespace restaurant.Controllers
{
    public class PayController : Controller
    {
        private InvoiceDAO invoiceDAO = new InvoiceDAO();
        private InvoiceDetailsDAO invoiceDetailsDAO = new InvoiceDetailsDAO();
        private TableDAO tableDAO = new TableDAO();

        // GET: Pay
        public ActionResult Index(int? page)
        {
            ViewBag.ListInvoice = invoiceDAO.GetAllUnpayInvoice();
            return View();
        }

        public PartialViewResult GetPaging(int? page)
        {
            var tables = tableDAO.GetAllTable();
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return PartialView("_ListTable",tables.OrderBy(table => table.id).ToPagedList(pageNumber, pageSize));
        }

        public ActionResult PayDetails(string invoiceID)
        {
            List<Table> tables = tableDAO.GetAllTableByInvoiceId(invoiceID);
            List<InvoiceDetail> invoiceDetails = new List<InvoiceDetail>();

            tables.ForEach(table =>
            {
                invoiceDetailsDAO.GetAllByInvoiceAndTable(invoiceID, table.id).ToList().ForEach(invoiceDetail =>
                {
                    invoiceDetails.Add(invoiceDetail);
                });
            });

            ViewBag.Invoice = invoiceDAO.GetInvoiceById(invoiceID);
            ViewBag.ListInvoiceDetails = invoiceDetails;
            ViewBag.ListTable = tableDAO.GetAllTableByInvoiceId(invoiceID);
            return View("Details");
        }

        public ActionResult PayInvoice(string invoiceID)
        {
            List<Table> tables = tableDAO.GetAllTableByInvoiceId(invoiceID);
            tables.ForEach(table =>
            {
                tableDAO.ChangeStatus(table.id);
            });
            invoiceDAO.SetOffStatus(invoiceID);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult AddInvoice(string customerName, string customerPhone)
        {
            Invoice invoice = new Invoice()
            {
                id = Common.CreateKey.Invoice(),
                customerName = customerName,
                customerPhone = customerPhone,
                status = true
            };
            invoiceDAO.Add(invoice);
            return Json(invoice, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public void AddTableForInvoice(string invoiceId, List<int> listTable)
        {
            tableDAO.AddTableForInvoice(invoiceId, listTable);
        }
    }
}

restaurant/Views/Pay/Index.cshtml
@model PagedList.IPagedList<Models.EF.Table>

@{
    ViewBag.Title = "Hóa đơn";
    ViewBag.SubTitle = "Danh sách hóa đơn";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<button class="btn btn-primary" role="button" data-toggle="modal" data-target="#modalAddInvoice">Thêm hóa đơn</button>

<!-- The Modal -->
<div class="modal" id="modalAddInvoice">
    <div class="modal-dialog modal-dialog-centered modal-xl">
        <div class="modal-content">

            <!-- Modal Header -->
            <div class="modal-header">
                <h4 class="modal-title">Thêm hóa đơn</h4>
                <button id="btnCloseModalPay" type="button" class="close" data-dismiss="modal">&times;</button>
            </div>

            <!-- Modal body -->
            <div class="modal-body row">

                <div class="col-md-5">
                    <div class="form-group">
                        <label for="customerName">Tên khách:</label>
                        <input type="text" class="form-control" id="customerName" placeholder="Nhập tên khách" name="customerName" required>
                    </div>
                    <div class="form-group">
                        <label for="customerPhone">Số điện thoại:</label>
                        <input type="text" class="form-control" id="customerPhone" placeholder="Nhập số điện thoại" name="customerPhone" required>
                    </div>
                    <button id="btn-add-invoice" type="submit" class="btn btn-primary" style="width: 100%; margin-bottom: 100px;">OK</button>
                </div>

                <div class="col-md-7">
                    <div id="modalAddTable" class="modal-body">

                        @{ Html.RenderAction("GetPaging", "Pay", new { page = 1 }); }

                    </div>
                </div>

            </div>

        </div>
    </div>
</div>

<div id="container-pay">

    <div>
        <table id="table-pay" class="table table-responsive-md">
            <thead>
                <tr>
                    <th>Mã hóa đơn</th>
                    <th>Tên khách</th>
                    <th> </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in ViewBag.ListInvoice)
                {
                    <tr>
                        <td>@item.id</td>
                        <td>@item.customerName</td>
                        <td><a href="@Url.Action("PayDetails", new { invoiceID = item.id})" class="btn btn-primary" role="button">Chi tiết</a></td>
                    </tr>
                }
            </tbody>
        </table>

    </div>

</div>