restaurant/Controllers/CartController.cs
using Models.DAO;
using restaurant.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;

namespace restaurant.Controllers
{
    public class CartController : Controller
    {
        ProductDAO productDAO = new ProductDAO();
        TableDAO tableDAO = new TableDAO();

        [Credential(roleID = "VIEW_CART")]
        public ActionResult Index()
        {
            List<Cart> carts = Session["cart"] as List<Cart>;
            ViewBag.ListCart = carts;
            return View();
        }

        public PartialViewResult GetPaging(int? page)
        {
            var tables = tableDAO.GetAllTable().Where(table => table.status == true);
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return PartialView("_ListTableCart", tables.OrderBy(table => table.id).ToPagedList(pageNumber, pageSize));
        }

        [HttpPost]
        [Credential(roleID = "ADD_CART")]
        public ActionResult AddCart(string productId)
        {
            if (Session["cart"] == null)
            {
                Session["cart"] = new List<Cart>();
            }

            var carts = Session["cart"] as List<Cart>;

            var name = carts.Find(item => item.productID == productId);
            if (name == null)
            {
                string productName = productDAO.GetNameByID(productId);
                Cart cart = new Cart(productId, productName, 1);
                carts.Add(cart);
            }

            return Json("true", JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        [Credential(roleID = "REMOVE_CART")]
        public ActionResult RemoveCart(string productId)
        {
            List<Cart> carts = Session["cart"] as List<Cart>;
            carts.Remove(carts.Find((cart => cart.productID == productId)));
            return Json("true", JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        [Credential(roleID = "UPDATE_CART")]
        public ActionResult UpdateCart(string productId, int quantity)
        {
            List<Cart> carts = Session["cart"] as List<Cart>;
            var item = carts.Find(cart => cart.productID == productId);
            item.quantity = quantity;
            return Json("true", JsonRequestBehavior.AllowGet);
        }

        public ActionResult RemoveSession()
        {
            Session.Remove("cart");
            return RedirectToAction("Index", "Gallery");
        }
    }
}

restaurant/Controllers/KitchenController.cs
using Models.DAO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace restaurant.Controllers
{
    public class KitchenController : Controller
    {

        private InvoiceDetailsDAO invoiceDetailsDAO = new InvoiceDetailsDAO();
        private ProductDAO productDAO = new ProductDAO();

        // GET: Kitchen
        public ActionResult Index()
        {
            ViewBag.ListOrder = invoiceDetailsDAO.GetAllWaiting();
            return View();
        }

        public ActionResult Complete(int invoiceDetailsID, string productId, int quantity)
        {
            invoiceDetailsDAO.SetStatusOff(invoiceDetailsID);
            productDAO.UpdateBuyCount(productId, quantity);
            return RedirectToAction("Index");
        }
    }
}

restaurant/Controllers/OrderController.cs
using Models.DAO;
using Models.EF;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using restaurant.Models;

namespace restaurant.Controllers
{
    public class OrderController : Controller
    {

        private InvoiceDAO invoiceDAO = new InvoiceDAO();
        private InvoiceDetailsDAO invoiceDetailsDAO = new InvoiceDetailsDAO();
        private ProductDAO productDAO = new ProductDAO();
        private TableDAO tableDAO = new TableDAO();

        [Credential(roleID = "VIEW_INVOICE_D")]
        public ActionResult Index(string tableID)
        {
            if (tableID == null)
                tableID = tableDAO.GetTableHasPeople().ToList()[0].id;
            SetViewBag(tableID);
            return View("Index");
        }

        private void SetViewBag(string tableID)
        {
            var invoiceID = invoiceDAO.GetLastInvoiceByTableId(tableID).id;
            ViewBag.TableID = tableID;
            ViewBag.InvoiceID = invoiceID;
            ViewBag.ListTable = new SelectList(tableDAO.GetAllTable().Where(table => table.status == true), "id", "id", tableID);
            ViewBag.ListOrder = invoiceDetailsDAO.GetByInvoiceAndTable(invoiceID, tableID).Where(x => x.status == true).ToList();
            ViewBag.ListInvoiceDetail = invoiceDetailsDAO.GetByInvoiceAndTable(invoiceID, tableID).Where(x => x.status == false);
        }
    }
}

restaurant/Views/Shared/_Layout.cshtml
@{
    var user = Session["user"] as Models.EF.User;
}

<!DOCTYPE html>
<html lang="vi">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>@ViewBag.Title</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/Site.css" rel="stylesheet" />
    <link href="~/Content/PagedList.css" rel="stylesheet" />
    <link href="~/Content/glyphicons.css" rel="stylesheet" />
    <link href="~/Content/simple-sidebar.css" rel="stylesheet" />

    <link href="~/Content/fontawesome.min.css" rel="stylesheet" />
    <link href="~/Content/brands.min.css" rel="stylesheet" />
    <link href="~/Content/solid.min.css" rel="stylesheet" />

    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>

    <script src="~/Scripts/jquery.signalR-2.4.0.min.js"></script>
    <script src="~/signalr/hubs"></script>
</head>

<body>

    <div class="d-flex" id="wrapper">

        <!-- Sidebar -->
        <div class="bg-light border-right" id="sidebar-wrapper">
            <div class="sidebar-heading"><span>Quản lý</span></div>
            <div class="list-group list-group-flush">
                <a href="/Gallery" class="list-group-item list-group-item-action bg-light"><i class="fas fa-book"></i> Thực đơn</a>
                <a href="/Kitchen" class="list-group-item list-group-item-action bg-light"><i class="fas fa-utensils"></i> Nhà bếp</a>
                <a href="/Order" class="list-group-item list-group-item-action bg-light"><i class="fas fa-table"></i> Xem thông tin bàn</a>
                @if (user != null && user.groupID == "Cashier")
                {
                    <a href="/Invoice" class="list-group-item list-group-item-action bg-light"><i class="fas fa-file-invoice-dollar"></i> Hóa đơn</a>
                }
                @if (user.groupID == "Admin")
                {
                    <a href="/Invoice" class="list-group-item list-group-item-action bg-light"><i class="fas fa-file-invoice-dollar"></i> Hóa đơn</a>
                    <a href="/Admin/User" class="list-group-item list-group-item-action bg-light"><i class="fas fa-user-alt"></i> Nhân viên</a>
                    <a href="/Admin/Product" class="list-group-item list-group-item-action bg-light"><i class="fas fa-cookie"></i> Món ăn</a>
                    <a class="list-group-item list-group-item-action bg-light" data-toggle="collapse" href="#collapseReport" aria-expanded="false" aria-controls="collapseReport">
                        <i class="fas fa-chart-pie"></i> Thống kê <i class="fas fa-angle-down" style="position: relative; left: 6px; top: 1px;"></i>
                    </a>
                    <ul class="collapse list-unstyled" id="collapseReport">
                        <li><a href="/Admin/Report/Revenue" class="list-group-item list-group-item-action bg-light"><i class="fas fa-money-check-alt"></i> Doanh thu</a></li>
                        <li><a href="/Admin/Report/FindInvoice" class="list-group-item list-group-item-action bg-light"><i class="fas fa-search"></i> Tìm kiếm</a></li>
                    </ul>
                }
            </div>
        </div>
        <!-- /#sidebar-wrapper -->
        <!-- Page Content -->
        <div id="page-content-wrapper">

            <nav id="nav-bar" class="navbar navbar-expand-lg navbar-light border-bottom">

                <div class="navbar-brand">
                    <i class="glyphicon glyphicon-transfer" role="button" id="menu-toggle"></i>
                    <h6 class="sub-title">@ViewBag.SubTitle</h6>
                </div>

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation" style="border: none">
                    <span class="glyphicon glyphicon-tasks"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
                        <li class="nav-item custom-navbar">

                        </li>
                        <li class="nav-item">
                            @{
                                if (user == null)
                                {
                                    <a class="nav-link" href="/Login">Đăng nhập</a>
                                }
                                else
                                {
                                    <a class="nav-link" href="/Login/Logout" style="color: #1a73e8;"> @user.accountName</a>
                                }
                            }
                        </li>
                    </ul>
                </div>
            </nav>

            <div id="body-layout" class="container-fluid">
                @RenderBody()
            </div>
        </div>
        <!-- /#page-content-wrapper -->

    </div>

    <script src="~/Scripts/custom.js"></script>
    @RenderSection("scripts", required: false)

    <!-- Menu Toggle Script -->
    <script>
        $("#menu-toggle").click(function (e) {
            e.preventDefault();
            $("#wrapper").toggleClass("toggled");
        });
    </script>

</body>

</html>

restaurant/Views/Shared/_LayoutClient.cshtml
<!DOCTYPE html>
<html lang="vi">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>@ViewBag.Title</title>

    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/Site.css" rel="stylesheet" />
    <link href="~/Content/PagedList.css" rel="stylesheet" />
    <link href="~/Content/glyphicons.css" rel="stylesheet" />
    <link href="~/Content/style.css" rel="stylesheet" />

    <link href="~/Content/fontawesome.min.css" rel="stylesheet" />
    <link href="~/Content/brands.min.css" rel="stylesheet" />
    <link href="~/Content/solid.min.css" rel="stylesheet" />

    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>

    <script src="~/Scripts/jquery.signalR-2.4.0.min.js"></script>
    <script src="~/signalr/hubs"></script>
</head>

<body>
    <header>
        <div class="top-nav">
            <div class="container">
                <nav class="navbar navbar-expand-lg navbar-light">
                    <a class="navbar-brand text-uppercase" href="index.html">Cafe In</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <div class="collapse navbar-collapse justify-content-center pr-md-4" id="navbarSupportedContent">
                        <ul class="navbar-nav ml-auto">
                            <li class="nav-item">
                                <a id="nav-link-home" class="nav-link" href="@Url.Action("Index", "Kitchen")">Nhà bếp</a>
                            </li>
                            <li class="nav-item">
                                <a id="nav-link-table" class="nav-link" href="@Url.Action("Index", "Order")">Xem bàn</a>
                            </li>
                            <li class="nav-item">
                                <a id="nav-link-gallery" class="nav-link" href="@Url.Action("Index","Gallery")">Menu</a>
                            </li>
                            <li class="nav-item">
                                <a id="nav-link-cart" class="nav-link" href="@Url.Action("Index", "Cart")">Giỏ hàng</a>
                            </li>
                        </ul>
                    </div>
                </nav>
            </div>
        </div>
    </header>
    <!-- //Navigation -->
    <section class="inner_banner">
        <div class="dot1">
        </div>
    </section>

    @RenderBody()


    <script src="~/Scripts/custom.js"></script>
    @RenderSection("scripts", required: false)

</body>

</html>